### ISSUE TITLE
Error: Used disallowed intents

### ISSUE THREAD

**Issue by logandoescode** [mayudev/revcord#18]
How do I fix this issue?
Terminal output:
```js
cumbook:revcord trippysloth$ npm start

> revcord@1.1.1 start
> node build/index.js

info db Connection has been established successfully.
info Revolt Logged in as RekuBridge
/Users/trippysloth/Documents/revcord/node_modules/@discordjs/ws/dist/index.js:1066
        throw new Error("Used disallowed intents");
              ^

Error: Used disallowed intents
    at WebSocketShard.onClose (/Users/trippysloth/Documents/revcord/node_modules/@discordjs/ws/dist/index.js:1066:15)
    at WebSocket.emit (node:events:511:28)
    at WebSocket.emitClose (/Users/trippysloth/Documents/revcord/node_modules/ws/lib/websocket.js:258:10)
    at TLSSocket.socketOnClose (/Users/trippysloth/Documents/revcord/node_modules/ws/lib/websocket.js:1264:15)
    at TLSSocket.emit (node:events:523:35)
    at node:net:334:12
    at TCP.done (node:_tls_wrap:588:7)

Node.js v20.3.1
cumbook:revcord trippysloth$ ```

**Comment by mayudev** [comment]
you forgot to do this:
Enable the Message Content Intent under Bot -> Privileged Gateway Intents. If you forget to do this, the bridge will only work one way (from Revolt to Discord) and messages from Discord will be empty.
It seems it just crashes now instead, I'll update that i guess.
