### ISSUE TITLE
DiscordAPIError: Missing Permissions

### ISSUE THREAD

**Issue by stratbasher** [mayudev/revcord#9]
Hello,

I am running revcord in Docker. I have both bots running and signed into Discord and Revolt. The bot in Revolt is in a role that has Masquerade permissions and the bot on Discord is in a role that has "Manage Webhooks" specifically enabled.

I also used all the checkboxes when generating the invitation link.

I'm getting the following in my logs whenever I try to connect channels:
```

revcord_1                | ERR! Discord DiscordAPIError: Missing Permissions
revcord_1                | ERR! Discord     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
revcord_1                | ERR! Discord     at processTicksAndRejections (node:internal/process/task_queues:96:5)
revcord_1                | ERR! Discord     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
revcord_1                | ERR! Discord     at async TextChannel.fetchWebhooks (/app/node_modules/discord.js/src/structures/BaseGuildTextChannel.js:125:18)
revcord_1                | ERR! Discord  DiscordAPIError: Missing Permissions
revcord_1                | ERR! Discord     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
revcord_1                | ERR! Discord     at processTicksAndRejections (node:internal/process/task_queues:96:5)
revcord_1                | ERR! Discord     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
revcord_1                | ERR! Discord     at async TextChannel.fetchWebhooks (/app/node_modules/discord.js/src/structures/BaseGuildTextChannel.js:125:18) {
revcord_1                | ERR! Discord   method: 'get',
revcord_1                | ERR! Discord   path: '/channels/<redacted>/webhooks',
revcord_1                | ERR! Discord   code: 50013,
revcord_1                | ERR! Discord   httpStatus: 403,
revcord_1                | ERR! Discord   requestData: { json: undefined, files: [] }
revcord_1                | ERR! Discord }
revcord_1                | ERR! Discord DiscordAPIError: Missing Permissions
revcord_1                | ERR! Discord     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
revcord_1                | ERR! Discord     at processTicksAndRejections (node:internal/process/task_queues:96:5)
revcord_1                | ERR! Discord     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
revcord_1                | ERR! Discord     at async TextChannel.fetchWebhooks (/app/node_modules/discord.js/src/structures/BaseGuildTextChannel.js:125:18)
revcord_1                | ERR! Discord  DiscordAPIError: Missing Permissions
revcord_1                | ERR! Discord     at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:350:13)
revcord_1                | ERR! Discord     at processTicksAndRejections (node:internal/process/task_queues:96:5)
revcord_1                | ERR! Discord     at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:51:14)
revcord_1                | ERR! Discord     at async TextChannel.fetchWebhooks (/app/node_modules/discord.js/src/structures/BaseGuildTextChannel.js:125:18) {
revcord_1                | ERR! Discord   method: 'get',
revcord_1                | ERR! Discord   path: '/channels/<redacted>/webhooks',
revcord_1                | ERR! Discord   code: 50013,
revcord_1                | ERR! Discord   httpStatus: 403,
revcord_1                | ERR! Discord   requestData: { json: undefined, files: [] }
revcord_1                | ERR! Discord }
```
![revolt](https://user-images.githubusercontent.com/4118916/227636819-1a3557ab-cbff-47d0-a10a-ded8480d04cb.PNG)
![discord](https://user-images.githubusercontent.com/4118916/227636823-7f4f37c5-8c4f-4fc6-824d-a3ad041c8688.png)

I'm not sure what I'm doing wrong or if this is a bug. Any assistance would be appreciated.

**Comment by mayudev** [comment]
The most likely reason is that at some point the permission to manage webhooks in the channel was overridden to be denied. Adding the Administrator permission just invalidated this override.

I've added an additional permission check, a clearer error message and and an entry in documentation explaining it.
